---
- hosts: all
  sudo: yes
  remote_user: ubuntu
  gather_facts: no
  vars:
    dest: "/home/ubuntu/db-backup" 
    s3Obj: ""

  tasks:
    - pip:
        name: boto3
        name: botocore
        
    - apt:
        name: mysql-client 
        state: latest
        update_cache: yes

    - name: GET operation
      s3:
        bucket: sprii-database-backups
        object: "{{ s3Obj }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        dest:  "{{ dest }}"
        mode: get
