---
- hosts: all
  sudo: yes
  remote_user: ubuntu
  gather_facts: no
  vars:
    dest: "/home/ubuntu/db-backup" 
    s3Obj: "https://s3.amazonaws.com/sprii-database-backups/magento-dump.sql"

  tasks:
    - pip:
        name: boto3
        name: botocore
        
    - name: GET operation
      aws_s3:
        bucket: sprii-database-backups
        object: "{{ s3Obj }}"
        dest:  "{{ dest }}"
        mode: get