---
- name: test how easy_install, pip
  hosts: all
  
  tasks:
  - name: Install easy_install
    sudo: yes
    apt:
      with_items:
        - python-setuptools
        - build-essential
        - mysql-client
        - python-pip

