---
- name: test how easy_install, pip
  hosts: all
  
  tasks:
  - name: Install easy_install
    sudo: yes
    apt:
      name: python-pip python-setuptools build-essential mysql-client
      
    update_cache: yes

