---
- name: test how easy_install, pip
  hosts: all
  
  tasks:
  - name: Install easy_install
    sudo: yes
    apt:
      name: python-pip 
      name: python-setuptools 
      name: build-essential 
      name: mysql-client
      
    update_cache: yes

