image: python:3.5.1

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y python-dev zip 
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install awscli
          - zip -r artifacts.zip *
          - aws s3 sync --delete . s3://test101-bit-s3

