---
- hosts: all
  sudo: yes
  remote_user: ubuntu
  gather_facts: no
  vars:
    file_path: "/var/lib/awx/projects/_19__docker" 

  tasks:
    - name : build docker
      become: yes
      become_user: root
      shell: |
      cd  "{{ file_path }}"
      docker build -t "test-api" .
      
    - name: run docker
      become: yes
      become_user: root
      command : docker run -it -p 80:9001 --name api test-api
