---
- hosts: all
  sudo: yes
  remote_user: ubuntu
  gather_facts: no
  vars:
    file_path: "/var/lib/awx/projects/_19__docker" 

- git:
    repo: https://github.com/frodood/ansible101.git
    dest: /home/ubuntu/ansible101
    version: master

  tasks:
    - name : build docker
      become: yes
      become_user: root
      shell: |
        cd  "{{ dest }}"
        docker build -t "test-api" .
      
    - name: run docker
      become: yes
      become_user: root
      command : docker run -it -p 80:9001 --name api test-api
