#!/bin/bash

function checkport {
        if nc -zv -w30 $1 $2 <<< '' &> /dev/null
        then
                echo "[+] Port $1/$2 is open"
        else
                echo "[-] Port $1/$2 is closed"
                if [ $2 == 9001 ]; then
                        docker restart sprii-api
                fi
}

checkport '127.0.0.1' 9001

